dbt_real_estate:
  outputs:

    dev:
      type: trino
      method: none
      user: admin
      password: ''
      database: iceberg
      host: localhost
      port: 8085
      schema: real-estate
      threads: 4

    prod:
      type: athena
      s3_staging_dir: s3://etl-project-athena-query-results-bucket-20220919/
      s3_data_dir: s3://real-estate-silver/
      region_name: ap-northeast-2
      database: awsdatacatalog
      work_group: primary
      schema: mart-real-estate
      aws_profile_name: 'etluser'
      # aws_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
      # aws_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
      threads: 4
      num_retries: 2

  target: dev
