
version: 2

models:
  - name: stg_apt_trade
    description: "아파트 매매 실거래가 데이터"
    columns:
      - name: apt_trade_id
        description: "유니크 해시 키"
        data_tests:
          - unique
          - not_null
      - name: aptNm
        data_tests:
          - not_null
      - name: buildYear
        data_tests:
          - not_null
      - name: sggCd
        data_tests:
          - not_null
      - name: umdNm
        data_tests:
          - not_null
  - name: stg_stan_regin_cd
    description: "법정동코드 데이터"
    columns:
      - name: stan_regin_cd_id
        data_tests:
          - unique
          - not_null
      - name: region_cd
        data_tests:
          - not_null
      - name: umdNm
        data_tests:
          - not_null
  - name: stg_br_title_info
    description: "건축물대장 표제부 조회 데이터"
    columns:
    - name: br_title_info_id
      description: "유니크 해시 키"
      data_tests:
        - unique
        - not_null
    - name: platPlc
      description: "대지위치"
      data_tests:
        - not_null
  - name: stg_br_recap_title_info
    description: "건축물대장 총괄표제부 조회 데이터"
    columns:
      - name: br_recap_title_info_id
        description: "유니크 해시 키"
        data_tests:
          - unique
          - not_null
      - name: platPlc
        description: "대지위치"
        data_tests:
          - not_null
  - name: stg_naver_land_geo_info
    description: "네이버부동산 동단위 위도경도 정보"
    columns:
      - name: naver_land_geo_info_id
        description: "유니크 해시 키"
        data_tests:
          - unique
          - not_null
  - name: stg_naver_land_complex_info_detail
    description: "네이버부동산 단지 상세 정보"
    columns:
      - name: naver_land_complex_info_detail_id
        description: "유니크 해시 키"
        data_tests:
          - unique
          - not_null

