
version: 2

models:
  - name: dim_stan_regin_cd
    description: "시군구 법정동 포함 코드"
  - name: dim_stan_regin_cd_gu
    description: "시군구 코드만 포함 코드"
  - name: fct_apt_trade
    description: "아파트 매매 실거래가"
  - name: dim_br_title_info
    description: "건축물대장 표제부, 아파트 동 단위"
  - name: dim_br_recap_title_info
    description: "건축물대장 총괄표제부, 아파트 전체 단위 묶음"
  - name: fct_apt_trade_detail
    description: "아파트 매매 실거래가 종합 정보"
  - name: dim_naver_land_geo_info
    description: "네이버부동산 동단위 위도경도 정보"
  # - name: dim_naver_land_complex_info
    # description: "네이버부동산 단지 정보"